<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div>
	<h2><i class="fa fa-star"></i> Commande payée</h2>

		<h3>Merci d'avoir commandé au 3WA Restaurant !</h3>

		<p data-order-step="success">Votre commande numéro <?= $_GET['orderId']?> a bien été enregistrée, elle vous sera livrée dans les plus brefs délais.</p>
		<p class="layout-center"><img alt="Commande payée" src="<?= $wwwUrl ?>/images/success.gif"></p>

		<a class="button button-primary" href="<?= $requestUrl ?>">Accueil</a>


	</div>
</body>
</html>

<script type="text/javascript">

	window.localStorage.removeItem('panier');
