<!DOCTYPE html>
<html lang="fr">
  <head>
    <link rel="stylesheet" href="style.css">
    <meta charset="utf-8">
    <title>Gestionnaire</title>
  </head>
  <body>
    <h1>Gestionnaire de tâches</h1>
    <form class="" action="add.php" method="post">

    <input type="checkbox" name="" value="">
    <legend>en retard</legend>
    <input type="checkbox" name="" value="">
    <legend>en retard</legend>
    <input type="checkbox" name="" value="">
    <legend>en retard</legend>

      <button type="button" name="erase">Supprimer</button>
  <fieldset class="" action="index.html" method="post">
    <legend>Informations sur la tâche</legend>
    <label for="title :">Titre :</label>
    <input type="text" name="title" value="">
    <label for="task :"> Tâche :</label>
    <input type="textarea" name="task" value="">

    <label for="date_end :">Date de fin :</label>
    <select name="date_end" id="Day">
      <option value="jour1">1</option>
      <option value="jour2">2</option>
      <option value="jour1">3</option>
      <option value="jour2">4</option>
      <option value="jour1">5</option>
      <option value="jour2">6</option>
      <option value="jour1">7</option>
      <option value="jour2">8</option>
      <option value="jour1">9</option>
      <option value="jour2">10</option>
      <option value="jour1">11</option>
      <option value="jour2">12</option>
      <option value="jour1">13</option>
      <option value="jour2">14</option>
      <option value="jour1">15</option>
      <option value="jour2">16</option>
      <option value="jour1">17</option>
      <option value="jour2">18</option>
      <option value="jour1">19</option>
      <option value="jour2">20</option>
      <option value="jour1">21</option>
      <option value="jour2">22</option>
      <option value="jour1">23</option>
      <option value="jour2">24</option>
      <option value="jour1">25</option>
      <option value="jour2">26</option>
      <option value="jour1">27</option>
      <option value="jour2">28</option>
      <option value="jour1">29</option>
      <option value="jour2">30</option>
      <option value="jour2">31</option>
    </select>

    <select name="date_end" id="month">
      <option value="jour1">1</option>
      <option value="jour2">2</option>
      <option value="jour1">3</option>
      <option value="jour2">4</option>
      <option value="jour1">5</option>
      <option value="jour2">6</option>
      <option value="jour1">7</option>
      <option value="jour2">8</option>
      <option value="jour1">9</option>
      <option value="jour2">10</option>
      <option value="jour1">11</option>
      <option value="jour2">12</option>
    </select>

    <select name="date_end" id="year">
      <option value="jour1">2018</option>
      <option value="jour2">2019</option>
      <option value="jour1">2020</option>
      <option value="jour2">2021</option>
    </select>

    <label for="priority">Priorité :</label>
    <input type="radio" name="" value="">
    <input type="radio" name="" value="">
    <input type="radio" name="" value="">

    <button type="submit" name="button">Ajouter</button>
  </fieldset>

  </form>
  </body>
</html>
