<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="style.css">
    <title>Bon de commande</title>
  </head>
  <body class="container">
    <h1>Bon de commande</h1>
    <h2>Liste des commandes</h2>

<table>
  <?php foreach  ($orders as $index => $order) {  ?>

      <tr>
        <td><a href="#"><?= $order['orderNumber'] ?></a></td>
        <td><?= $order['orderDate'] ?></td>
        <td><?= $order['shippedDate'] ?></td>
        <td><?= $order['status'] ?></td>
      </tr>

  <?php } ?>
</table>
  </body>
</html>
